name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build the Docker image
      run: docker build . --tag nothing:latest 
    - name: Tag the Docker image again!? silly shit
      run: docker tag nothing:latest ghcr.io/minionbots/nothing/api:latest
    - name: Push the Docker image
      run: docker push ghcr.io/minionbots/nothing/api:latest
