name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: What a bunch of morons, a separate step just to get the lowercase repo name.. am I the only one around here !?
      uses: actions/github-script@v4
      id: repo_slug
      with:
        result-encoding: string
        script: return `ghcr.io/${github.repository.toLowerCase()}`
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/(${{ steps.repo_slug.outputs.result }}).toLowerCase()
          
